# Generated by Django 5.1.2 on 2024-10-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_order_payment_completed_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
