# Generated by Django 5.1.2 on 2024-10-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_alter_review_rating_alter_review_review_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
