# Generated by Django 5.1.2 on 2024-10-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
